title: CEAMLS SAIRI Website Summer 2025 
logo: assests/images/logo.png
description: Hi! My name is Ta'quavion Johnson and this is my CEAMLS SAIRI Website for Summer 2025.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
future: true
