#!/bin/sh

set -e

# Warn if RubyGems is outdated
echo "👉 Checking RubyGems version..."
gem update --system

# Step 1: Build the site
echo "🚧 Building Jekyll site..."
bundle exec jekyll build

# Step 2: Run HTML Proofer with improved error handling
echo "🔍 Running HTML Proofer..."
bundle exec htmlproofer ./_site \
  --check-html \
  --check-sri \
  --only-4xx \
  --file-ignore "./_site/about-me.html" \
  --url-ignore "^https://(www\.)?linkedin\.com"
  

# Step 3: Run Rubocop for style checks
echo "🧹 Running Rubocop..."
bundle exec rubocop -D --config .rubocop.yml

# Step 4: HTML validation script
echo "🧪 Validating HTML..."
bundle exec script/validate-html

# Step 5: Build the gem
echo "📦 Building the theme gem..."
gem build jekyll-theme-minimal.gemspec
